"""
Data imported from dcss source code
"""

# From \source\job-data.h
jobs = {
    "Abyssal Knight": "AK",
    "Air Elementalist": "AE",
    "Arcane Marksman": "AM",
    "Artificer": "Ar",
    "Assassin": "As",
    "Berserker": "Be",
    "Chaos Knight": "CK",
    "Conjurer": "Cj",
    "Earth Elementalist": "EE",
    "Enchanter": "En",
    "Fighter": "Fi",
    "Fire Elementalist": "FE",
    "Gladiator": "Gl",
    "Hunter": "Hu",
    "Ice Elementalist": "IE",
    "Monk": "Mo",
    "Necromancer": "Ne",
    "Skald": "Sk",
    "Summoner": "Su",
    "Transmuter": "Tm",
    "Venom Mage": "VM",
    "Wanderer": "Wn",
    "Warper": "Wr",
    "Wizard": "Wz",
    "Death Knight": "DK",
    "Healer": "He",
    "Jester": "Jr",
    "Priest": "Pr",
    "Stalker": "St"
}


# from \source\species-data.h
species = {
    "Centaur": "Ce",
    "Deep Dwarf": "DD",
    "Deep Elf": "DE",
    "Demigod": "Dg",
    "Draconian": "Dr",
    "Red Draconian": "Dr",
    "White Draconian": "Dr",
    "Green Draconian": "Dr",
    "Yellow Draconian": "Dr",
    "Grey Draconian": "Dr",
    "Black Draconian": "Dr",
    "Purple Draconian": "Dr",
    "Mottled Draconian": "Dr",
    "Pale Draconian": "Dr",
    "Demonspawn": "Ds",
    "Felid": "Fe",
    "Formicid": "Fo",
    "Ghoul": "Gh",
    "Gargoyle": "Gr",
    "Halfling": "Ha",
    "High Elf": "HE",
    "Hill Orc": "HO",
    "Human": "Hu",
    "Kobold": "Ko",
    "Merfolk": "Mf",
    "Minotaur": "Mi",
    "Mummy": "Mu",
    "Naga": "Na",
    "Ogre": "Og",
    "Octopode": "Op",
    "Spriggan": "Sp",
    "Tengu": "Te",
    "Troll": "Tr",
    "Vampire": "Vp",
    "Vine Stalker": "VS",
    "Sludge Elf": "SE",
    "Lava Orc": "LO",
    "Djinni": "Dj"
}
